name: CD
on:
  workflow_call:
    inputs:
      MainBranch: 
        description: "The Deploy branch"
        required: true
        type: string
    secrets:
      DB_NAME: {}
      DB_USER: {}
      DB_PASS: {}
      DB_HOST: {}
      DB_PORT: {}
      SH_HOST: {}
      SH_USER: {}
      SH_KEYY: {}
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Execute remote SSH commands
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SH_HOST }}
          username: ${{ secrets.SH_USER }}
          key: ${{ secrets.SH_KEYY }}
          script: |
            cd ~/actions-runner/_work/nd_server/nd_server/dist
            pm2 describe nd_serv > /dev/null
            if [ $? -eq 0 ]; then
               pm2 restart nd_serv
            else
               DB_NAME=${{ secrets.DB_NAME }} \
               DB_USER=${{ secrets.DB_USER }} \
               DB_PASS=${{ secrets.DB_PASS }} \
               DB_HOST=${{ secrets.DB_HOST }} \
               pm2 start main.js --name "nd_serv"
            fi

      


