name: CI
on:
  push:
    branches: ["test"]
    workflow_dispatch:
jobs:
  tests:
    uses: ./.github/workflows/test.yml
    with:
      testBranch: "test"

  build:
    needs: tests
    runs-on: self-hosted
    steps:
      name: "Echo build"
      run: echo "Build successful"
