name: CI/CD Pipeline
on:
  push:
    branches: ["main"]
  workflow_dispatch:
jobs:
  tests:    
    uses: ./.github/workflows/test.yml
    with:
      testBranch: "test"    
    secrets:
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASS: ${{ secrets.DB_PASS }}
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_PORT: ${{ secrets.DB_PORT }}

  build:
    needs: tests
    runs-on: self-hosted
    steps:
     - name: "Echo build"
       run: echo "Build successful"
