name: tests
on:
  push:
    branches: ["test"]
  workflow_dispatch:
jobs:
  test:
    runs-on: self-hosted
    steps:
      - name: Echo Test
        run: echo "Hello, GitHub Actions!"

      - name: Get repository code
        uses: actions/checkout@v3

      - name: Set Up NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: "23"

      - name: Install dependencies
        run: npm install

      - name: Run Tests
        env:
          NODE_ENV: test
          DB_NAEM: ${{ secrets.DB_NAME }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_PORT: ${{ secrets.DB_PORT }}

        run: npm test
