name: CI/CD Pipeline
on:
  push:
    branches: ["main"]
  workflow_dispatch:
jobs:
  CI:
    uses: ./.github/workflows/CI.yml
    with:
      mainBranch: "main"
    secrets:
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASS: ${{ secrets.DB_PASS }}
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_PORT: ${{ secrets.DB_PORT }}

  CD:
    needs: tests
    runs-on: self-hosted
    steps:
      - name: "Echo build STATUS:"
        run: echo "Build successful"


