name: tests
on: 
  push:
    branches: ["test"]
  workflow_dispatch:
jobs:
  test:
    runs-on: self-hosted
    steps:
        - name: Print Current Branch
          run: echo "Current branch is ${{ github.ref }}"
          
        - name: Get repository code
        - uses: actions/checkout@v3

        - name: Set Up NodeJS
        - uses: actions/setup-node@v3         
        
        - name: Install dependencies
          run: npm install
          
        - name: Run Tests
          run: npm test

